"""Builds the machine contract of DR-LAB-SC-1.1 from its LinkML sources (run with the LinkML environment).

    .venv-linkml\\Scripts\\python.exe contract/tools/build.py           # lint, validate, check, generate
    .venv-linkml\\Scripts\\python.exe contract/tools/build.py --check   # regenerate in memory, compare with the files

Sources (the only place the machine contract is written):
    contract/schema/dr_lab_sc.yaml       the LinkML schema (classes, slots, enums, rules), every element anchored in SC-1.1
    contract/registry/*.yaml             the registry: instance data of class Registry (profiles BASE-24, NOW-1.0)
Products (committed; never edited by hand; the runtime reads them, LinkML is not needed at runtime):
    contract/build/registry.json         the merged, validated registry with the SHA-256 stamps of every source
    contract/build/runtime_spec.json     the structural rules of every class for lab/contract.py (from SchemaView)
    contract/build/dr_lab_sc.schema.json the JSON Schema generated by LinkML (used by tests/contract_sc11.py)

Steps: linkml-lint (project config) -> metamodel validation -> each registry file and the merged registry validated
against class Registry (closed world) -> referential integrity and unique ids -> semantic checks of the registry that
LinkML cannot express (one claim form per estimand and its class admissible on every case set the estimand allows;
reference definitions exist in lab/contract.py; every estimand has an estimator) -> generation. The products are
deterministic (no time stamps) so --check proves they still equal what the sources produce.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from importlib.metadata import version
from pathlib import Path

import yaml
from linkml.generators.jsonschemagen import JsonSchemaGenerator
from linkml.validator import Validator
from linkml.validator.plugins import JsonschemaValidationPlugin
from linkml_runtime.utils.schemaview import SchemaView

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "contract" / "schema" / "dr_lab_sc.yaml"
LINT = ROOT / "contract" / "schema" / "linkml-lint.yaml"
REG_DIR = ROOT / "contract" / "registry"
OUT = ROOT / "contract" / "build"
DOC = "spec/DR-LAB-Semantic-Contract-1.1-(patched).md"
EDITION = "DR-LAB-SC-1.1"


def sha256_lf(p):
    return hashlib.sha256(Path(p).read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def rel(p):
    return str(Path(p).resolve().relative_to(ROOT)).replace("\\", "/")


def dumps(obj):
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, indent=1) + "\n"


def fail(msgs):
    for m in msgs: print("  FAIL", m)
    sys.exit(1)


def runtime_spec(sv):
    """The structural rules the runtime gate applies, taken from LinkML's own induced view of the schema."""
    classes, enums = {}, {}
    for name in sorted(sv.all_enums()):
        enums[name] = sorted(sv.get_enum(name).permissible_values)
    for name in sorted(sv.all_classes()):
        c = sv.get_class(name)
        slots = {}
        designator = None
        for s in sv.class_induced_slots(name):
            rng = s.range or sv.schema.default_range or "string"
            inlined = bool(s.inlined or s.inlined_as_list)
            if rng in sv.all_classes() and not sv.get_identifier_slot(rng): inlined = True
            d = dict(range=rng, required=bool(s.required or s.identifier), multivalued=bool(s.multivalued), inlined=inlined)
            for k, a in (("min", "minimum_value"), ("max", "maximum_value"), ("min_card", "minimum_cardinality"), ("max_card", "maximum_cardinality")):
                if getattr(s, a, None) is not None: d[k] = getattr(s, a)
            if s.pattern: d["pattern"] = s.pattern
            if s.designates_type: designator = s.name
            slots[s.name] = d
        rules = []
        for r in c.rules or []:
            pre = {k: v.equals_string for k, v in (r.preconditions.slot_conditions or {}).items()} if r.preconditions else {}
            post = {}
            for k, v in ((r.postconditions.slot_conditions or {}).items() if r.postconditions else []):
                cond = {}
                if v.required: cond["required"] = True
                if v.equals_string is not None: cond["equals"] = v.equals_string
                if str(v.value_presence or "") == "ABSENT": cond["absent"] = True
                if v.minimum_value is not None: cond["min"] = v.minimum_value
                post[k] = cond
            rules.append(dict(pre=pre, post=post, description=r.description))
        classes[name] = dict(abstract=bool(c.abstract), slots=slots, rules=rules, designator=designator,
                             descendants=sorted(sv.class_descendants(name, reflexive=False)))
    return dict(schema=sv.schema.name, version=sv.schema.version, classes=classes, enums=enums)


def page_registry(merged, stamps):
    """What the page embeds (design/sozvezdiya-24/src/build.py): the estimands and claim forms it may show, with their
    labels, the fact forms, the roles of the case sets, and the registry hash the server's envelopes carry."""
    def labels(form):
        out = {}
        for lb in form.get("labels") or []:
            out.setdefault(lb["key"], {})[lb["view"]] = lb["text_ru"]
        return out
    est = {e["id"]: dict(profile=e["profile"], q4=e["q4_case_set"], measure=e["q7_measure"], unknown=e["q8_unknown"],
                         params=[p["name"] for p in e.get("parameters") or []]) for e in merged.get("estimands", [])}
    forms = {f["estimand"]: dict(id=f["id"], claim_class=f["claim_class"], value_form=f["value_form"], labels=labels(f))
             for f in merged.get("claim_forms", [])}
    facts = {f["id"]: dict(record=f["record_class"], labels=labels(f)) for f in merged.get("fact_forms", [])}
    roles = {c["id"]: c["role"] for c in merged.get("case_sets", [])}
    return dict(edition=EDITION, registry_hash=stamps["registry_sha256"][:16], estimands=est, forms=forms, facts=facts, case_sets=roles)


def load_registry():
    files = sorted(REG_DIR.glob("*.yaml"))
    parts, merged = {}, {"registry_part": "merged"}
    for f in files:
        d = yaml.safe_load(f.read_text(encoding="utf-8"))
        parts[f] = d
        for k, v in d.items():
            if isinstance(v, list): merged.setdefault(k, []).extend(v)
    return files, parts, merged


def references(sv, merged):
    """Every reference (a slot whose range is a class with an identifier, not inlined) must resolve to an instance of
    that class or of a descendant; ids are unique across the registry."""
    errs, ids = [], {}
    coll_class = {s.name: s.range for s in sv.class_induced_slots("Registry") if s.multivalued}
    for coll, items in merged.items():
        if not isinstance(items, list): continue
        cls = coll_class[coll]
        idslot = sv.get_identifier_slot(cls)
        for it in items:
            key = it.get(idslot.name) if idslot else None
            if key is None: continue
            if key in ids: errs.append(f"duplicate id {key}")
            ids[key] = cls

    def check(obj, cls, where):
        for s in sv.class_induced_slots(cls):
            v = obj.get(s.name)
            if v is None: continue
            rng = s.range
            if rng not in sv.all_classes(): continue
            vals = v if isinstance(v, list) else [v]
            inlined = s.inlined or s.inlined_as_list or not sv.get_identifier_slot(rng)
            for x in vals:
                if inlined and isinstance(x, dict): check(x, x.get("claim_class") or rng, f"{where}.{s.name}")
                elif isinstance(x, str):
                    ok = x in ids and (ids[x] == rng or ids[x] in sv.class_descendants(rng))
                    if not ok: errs.append(f"{where}.{s.name}: {x} is not a {rng}")
    for coll, items in merged.items():
        if not isinstance(items, list): continue
        for it in items: check(it, coll_class[coll], f"{coll}:{it.get('id', it.get('clause'))}")
    return errs, ids


def semantic_checks(merged, reg_file, spec_file):
    """What LinkML rules cannot express: cross-object consistency of the registry, using the runtime's own rules
    (lab/contract.py, pointed at the freshly generated products before they are written)."""
    sys.path.insert(0, str(ROOT / "lab"))
    import contract as C                                      # the same admissibility rule the server applies
    C.REGISTRY_FILE, C.SPEC_FILE = reg_file, spec_file
    C._load()
    errs = []
    est = {e["id"]: e for e in merged.get("estimands", [])}
    forms = {}
    for f in merged.get("claim_forms", []): forms.setdefault(f["estimand"], []).append(f)
    for eid, e in est.items():
        fs = forms.get(eid, [])
        if len(fs) != 1: errs.append(f"{eid}: {len(fs)} claim forms (exactly one required)"); continue
        for cs in e["q4_case_set"]:
            adm = C.admissible_claims(eid, cs)
            if fs[0]["claim_class"] not in adm: errs.append(f"{eid} on {cs}: form class {fs[0]['claim_class']} not admissible ({sorted(adm)})")
    for f in merged.get("claim_forms", []):
        if f["estimand"] not in est: errs.append(f"{f['id']}: unknown estimand")
    for f in merged.get("claim_forms", []) + merged.get("fact_forms", []):
        seen = set()
        for lb in f.get("labels") or []:
            k = (lb["key"], lb["view"])
            if k in seen: errs.append(f"{f['id']}: label {k} registered twice (the page could show either)")
            seen.add(k)
    covered = {x for s in merged.get("estimators", []) for x in s["estimands"]}
    for eid in est:
        if eid not in covered: errs.append(f"{eid}: no estimator")
    for coll in ("outcomes", "estimators"):
        for it in merged.get(coll, []):
            ref = it["reference_definition"]
            if not ref.startswith("lab/contract.py::") or not callable(getattr(C, ref.split("::")[1], None)):
                errs.append(f"{it['id']}: reference definition {ref} does not exist")
    for it in merged.get("predictive_admissions", []) + merged.get("policies", []) + merged.get("authorities", []):
        errs.append(f"{it['id']}: SC-1.1 defines no predictive admission, policy or action authority in this edition (§11, §14.3)")
    return errs


def build(check=False):
    print("DR-LAB-SC-1.1 · building the machine contract")
    r = subprocess.run([str(Path(sys.executable).parent / "linkml-lint"), "-c", str(LINT), str(SCHEMA)], capture_output=True, text=True, encoding="utf-8")
    if r.returncode != 0: fail(["linkml-lint: " + (r.stdout + r.stderr)[-2000:]])
    print("  ok   linkml-lint (project configuration)")
    sv = SchemaView(str(SCHEMA))
    validator = Validator(str(SCHEMA), validation_plugins=[JsonschemaValidationPlugin(closed=True)])
    files, parts, merged = load_registry()
    errs = []
    for f, d in parts.items():
        rep = validator.validate(d, "Registry")
        errs += [f"{rel(f)}: {res.message}" for res in rep.results]
    rep = validator.validate(merged, "Registry")
    errs += [f"merged registry: {res.message}" for res in rep.results]
    if errs: fail(errs[:40])
    print(f"  ok   {len(files)} registry files and the merged registry valid against class Registry (closed world)")
    rerrs, ids = references(sv, merged)
    if rerrs: fail(rerrs[:40])
    print(f"  ok   referential integrity: {len(ids)} ids, every reference resolves to its class")
    spec = runtime_spec(sv)
    jschema = JsonSchemaGenerator(str(SCHEMA), top_class="Registry", include_range_class_descendants=True).serialize()
    spec_text = dumps(spec)
    reg_text_body = dumps(merged)
    sources = {rel(SCHEMA): sha256_lf(SCHEMA), DOC: sha256_lf(ROOT / DOC)}
    for f in files: sources[rel(f)] = sha256_lf(f)
    stamps = dict(edition=EDITION, document=DOC, document_sha256_lf=sources[DOC], schema_sha256_lf=sources[rel(SCHEMA)],
                  sources=dict(sorted(sources.items())), linkml=version("linkml"), runtime_spec_sha256=hashlib.sha256(spec_text.encode()).hexdigest(),
                  registry_sha256=hashlib.sha256(reg_text_body.encode()).hexdigest())
    reg_text = dumps(dict(stamps=stamps, registry=merged))
    page_text = dumps(page_registry(merged, stamps))
    products = {OUT / "registry.json": reg_text, OUT / "runtime_spec.json": spec_text, OUT / "page_registry.json": page_text,
                OUT / "dr_lab_sc.schema.json": jschema if jschema.endswith("\n") else jschema + "\n"}
    edition = next((e for e in merged.get("editions", []) if e["id"] == EDITION), None)
    if edition is None or edition["document_sha256_lf"] != sources[DOC]:
        fail([f"the registry pins {EDITION} at {edition and edition['document_sha256_lf']}, the document is {sources[DOC]}: re-reconcile the schema with the changed contract text before rebuilding"])
    print(f"  ok   {EDITION} pinned at its SHA-256 (LF) {sources[DOC][:16]}…")
    with tempfile.TemporaryDirectory() as tmp:            # the runtime's own rules, run on the new products first
        t_reg, t_spec = Path(tmp) / "registry.json", Path(tmp) / "runtime_spec.json"
        t_reg.write_text(reg_text, encoding="utf-8", newline="\n")
        t_spec.write_text(spec_text, encoding="utf-8", newline="\n")
        serr = semantic_checks(merged, t_reg, t_spec)
    if serr: fail(serr[:40])
    print("  ok   semantic checks: one admissible claim form per estimand, estimators, reference definitions, no C2 / C3 grounds")
    if check:
        diff = [rel(p) for p, t in products.items() if not p.exists() or p.read_text(encoding="utf-8").replace("\r\n", "\n") != t]
        if diff: fail([f"{d} is not what the sources produce (run contract/tools/build.py)" for d in diff])
        print("  ok   the committed products equal what the sources produce")
    else:
        OUT.mkdir(parents=True, exist_ok=True)
        for p, t in products.items(): p.write_text(t, encoding="utf-8", newline="\n")
        print("  ok   wrote " + ", ".join(rel(p) for p in products))
    print("BUILT" if not check else "IN SYNC")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    build(ap.parse_args().check)
