(()=>{'use strict';
const SESS={ADR:{start:-270,formed:-210,end:120},ODR:{start:180,formed:240,end:510},RDR:{start:570,formed:630,end:960}};
const $=s=>document.querySelector(s),cv=$('#cv'),c=cv.getContext('2d'),tip=$('#tip'),panel=$('#panel');
const state={session:'RDR',mode:'R',at:null,day:null,fam:null,hover:null,selected:null,hit:[]};
const colors={bg:'#0d1016',grid:'#202734',text:'#cfd4dc',muted:'#7f8b9c',up:'#37b89d',dn:'#e36b72',R:'#e28a8f',X:'#5fc6a8',slice:'#77a9ff',idr:'#a9b4c4',dr:'#d8dee8'};
const pct=(n,d)=>d?((100*n/d).toFixed(n&&100*n/d<10?1:0)+'%'):'—';
const clk=t=>{let x=((Math.round(t)%1440)+1440)%1440;return String(Math.floor(x/60)).padStart(2,'0')+':'+String(x%60).padStart(2,'0')};
function esc(s){return String(s).replace(/[&<>]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[ch]))}
function init(){ $('#sessions').innerHTML=Object.keys(SESS).map(k=>'<button data-s="'+k+'">'+k+'</button>').join('');
$('#sessions').addEventListener('click',e=>{const k=e.target.dataset.s;if(!k)return;state.session=k;state.at=null;state.selected=null;load()});
$('#modes').addEventListener('click',e=>{const m=e.target.dataset.mode;if(!m)return;state.mode=m;state.selected=null;syncButtons();draw()});
$('#back').onclick=()=>step(-5);$('#forward').onclick=()=>step(5);$('#live').onclick=()=>{state.at=null;load()};
cv.addEventListener('mousemove',move);cv.addEventListener('mouseleave',()=>{tip.hidden=true;state.hover=null;draw()});cv.addEventListener('click',click);window.addEventListener('resize',draw);load()}
function syncButtons(){document.querySelectorAll('#sessions button').forEach(b=>b.classList.toggle('on',b.dataset.s===state.session));document.querySelectorAll('#modes button').forEach(b=>b.classList.toggle('on',b.dataset.mode===state.mode))}
function step(d){const s=SESS[state.session],now=state.day?Math.floor(state.day.now/5)*5:s.formed;let a=state.at==null?now:state.at;a=Math.max(s.start,Math.min(s.end,a+d));state.at=a;load()}
async function load(){syncButtons();panel.innerHTML='<div class="note">Загрузка…</div>';try{const day=await fetch('/api/day?instrument=NQ').then(r=>r.json());state.day=day;if(day.status!=='ok')throw new Error(day.message||'Нет данных');const q='/api/family-v1?instrument=NQ&session='+state.session+(state.at==null?'':'&at='+state.at);state.fam=await fetch(q).then(r=>r.json());$('#cond').textContent=state.fam.cond||state.session+' · '+(state.fam.status||'');draw()}catch(e){state.fam=null;panel.innerHTML='<div class="err">'+esc(e.message)+'</div>';draw()}}
function dims(){const dpr=window.devicePixelRatio||1,w=cv.clientWidth,h=cv.clientHeight;if(cv.width!==Math.round(w*dpr)||cv.height!==Math.round(h*dpr)){cv.width=Math.round(w*dpr);cv.height=Math.round(h*dpr)}c.setTransform(dpr,0,0,dpr,0,0);const right=state.mode==='PATH'?56:126,bottom=state.mode==='PATH'?30:84;return{w,h,plot:{x:48,y:16,w:w-right-48,h:h-bottom-16},right,bottom}}
function projected(u){const t=state.fam.today;return t.edge+t.direction*u*t.width}
function context(){const f=state.fam,s=SESS[state.session],obs=f&&f.obs!=null?f.obs:(state.at??(state.day?.now||s.formed));const known=(state.day?.bars||[]).filter(b=>b[0]+5<=obs&&b[0]>=s.start-5&&b[0]<s.end).map(b=>({t:b[0],o:b[1],h:b[2],l:b[3],cl:b[4]}));let lo=Infinity,hi=-Infinity;known.forEach(b=>{lo=Math.min(lo,b.l);hi=Math.max(hi,b.h)});if(f&&f.status==='ok'){[f.today.drL,f.today.drH,f.today.idrL,f.today.idrH].forEach(p=>{lo=Math.min(lo,p);hi=Math.max(hi,p)});if(state.mode!=='PATH')f.members.forEach(m=>{const u=state.mode==='R'?m.r:m.x;if(u!=null){const p=projected(u);lo=Math.min(lo,p);hi=Math.max(hi,p)}});else f.members.forEach(m=>(m.path_cl||[]).forEach(u=>{if(u!=null){const p=projected(u);lo=Math.min(lo,p);hi=Math.max(hi,p)}}))}if(!isFinite(lo)){lo=0;hi=1}const pad=Math.max((hi-lo)*.08,1);return{s,obs,known,p0:lo-pad,p1:hi+pad}}
function scales(g,ctx){const x0=ctx.s.start-20,x1=ctx.s.end+10;return{X:t=>g.plot.x+(t-x0)/(x1-x0)*g.plot.w,Y:v=>g.plot.y+(ctx.p1-v)/(ctx.p1-ctx.p0)*g.plot.h,P:y=>ctx.p1-(y-g.plot.y)/g.plot.h*(ctx.p1-ctx.p0),T:x=>x0+(x-g.plot.x)/g.plot.w*(x1-x0)}}
function draw(){const g=dims();c.clearRect(0,0,g.w,g.h);c.fillStyle=colors.bg;c.fillRect(0,0,g.w,g.h);const f=state.fam,ctx=context(),q=scales(g,ctx);state.hit=[];grid(g,ctx,q);if(f&&f.status==='ok'){levels(g,ctx,q);state.mode==='PATH'?pathMap(g,ctx,q):eventMap(g,ctx,q)}candles(g,ctx,q);slice(g,ctx,q);c.strokeStyle='#3a4352';c.strokeRect(g.plot.x+.5,g.plot.y+.5,g.plot.w,g.plot.h);if(!f||f.status!=='ok')empty(g,f);syncButtons();renderPanel()}
function grid(g,ctx,q){c.strokeStyle=colors.grid;c.lineWidth=1;c.font='11px system-ui';c.fillStyle=colors.muted;for(let t=Math.ceil((ctx.s.start-20)/30)*30;t<=ctx.s.end;t+=30){const x=Math.round(q.X(t))+.5;c.beginPath();c.moveTo(x,g.plot.y);c.lineTo(x,g.plot.y+g.plot.h);c.stroke();c.fillText(clk(t),x+3,g.plot.y+g.plot.h+17)}for(let i=0;i<=5;i++){const y=g.plot.y+i*g.plot.h/5;c.beginPath();c.moveTo(g.plot.x,y);c.lineTo(g.plot.x+g.plot.w,y);c.stroke();const p=ctx.p1-(ctx.p1-ctx.p0)*i/5;c.fillText(p.toFixed(1),4,y+4)}}
function levels(g,ctx,q){const t=state.fam.today;[[t.drH,'DR',false],[t.drL,'DR',false],[t.idrH,'IDR',true],[t.idrL,'IDR',true]].forEach(([p,n,d])=>{const y=q.Y(p);c.strokeStyle=d?colors.idr:colors.dr;c.globalAlpha=.55;c.setLineDash(d?[5,4]:[]);c.beginPath();c.moveTo(q.X(ctx.s.start),y);c.lineTo(q.X(ctx.s.end),y);c.stroke();c.setLineDash([]);c.globalAlpha=1;c.fillStyle=colors.muted;c.fillText(n,q.X(ctx.s.formed)+3,y-3)})}
function candles(g,ctx,q){const bs=Math.max(2,g.plot.w*5/(ctx.s.end-ctx.s.start+30));ctx.known.forEach(b=>{const x=q.X(b.t+2.5),col=b.cl>=b.o?colors.up:colors.dn;c.strokeStyle=col;c.fillStyle=col;c.beginPath();c.moveTo(x,q.Y(b.h));c.lineTo(x,q.Y(b.l));c.stroke();const y=Math.min(q.Y(b.o),q.Y(b.cl)),hh=Math.max(1,Math.abs(q.Y(b.o)-q.Y(b.cl)));c.fillRect(x-Math.max(1,bs*.28),y,Math.max(2,bs*.56),hh)})}
function slice(g,ctx,q){const x=q.X(Math.floor(ctx.obs/5)*5);c.strokeStyle=colors.slice;c.globalAlpha=.7;c.setLineDash([3,4]);c.beginPath();c.moveTo(x,g.plot.y);c.lineTo(x,g.plot.y+g.plot.h);c.stroke();c.setLineDash([]);c.globalAlpha=1;c.fillStyle=colors.slice;c.fillText(state.at==null?'сейчас':clk(ctx.obs),x+4,g.plot.y+12)}
function eventData(){const key=state.mode==='R'?'r':'x',tk=state.mode==='R'?'tr':'tx';return(state.fam?.members||[]).filter(m=>m.event_status==='known'&&m[key]!=null&&m[tk]!=null).map((m,i)=>({i,m,u:m[key],t:m[tk]}))}
function eventMap(g,ctx,q){const data=eventData(),col=colors[state.mode];c.fillStyle=col;data.forEach(d=>{const x=q.X(d.t+2.5),y=q.Y(projected(d.u));c.globalAlpha=.72;c.beginPath();c.arc(x,y,3.1,0,Math.PI*2);c.fill();state.hit.push({k:'event',x,y,r:7,d})});c.globalAlpha=1;priceHist(g,ctx,q,data,col);timeHist(g,ctx,q,data,col)}
function priceHist(g,ctx,q,data,col){const N=state.fam.n||1,bins=new Map();data.forEach(d=>{const k=Math.floor((d.u+1e-10)*10)/10;bins.set(k,(bins.get(k)||0)+1)});const max=Math.max(1,...bins.values()),x0=g.plot.x+g.plot.w+8,w=Math.max(44,g.right-22);for(const[k,n]of bins){const y0=Math.min(q.Y(projected(k)),q.Y(projected(k+.1))),y1=Math.max(q.Y(projected(k)),q.Y(projected(k+.1))),bw=w*n/max;c.fillStyle=col;c.globalAlpha=.28;c.fillRect(x0,y0,bw,Math.max(2,y1-y0));c.globalAlpha=1;if(y1-y0>10){c.fillStyle=colors.text;c.font='10px system-ui';c.fillText(pct(n,N),x0+2,y0+10)}state.hit.push({k:'pbin',x:x0,y:y0,w,yh:Math.max(3,y1-y0),bin:k,n,N})}if(state.selected?.type==='price'){const k=state.selected.bin,n=bins.get(k)||0,ya=q.Y(projected(k)),yb=q.Y(projected(k+.1)),yt=Math.min(ya,yb),yb2=Math.max(ya,yb);c.strokeStyle=col;c.lineWidth=2;c.beginPath();c.moveTo(g.plot.x+g.plot.w-5,yt);c.lineTo(g.plot.x+g.plot.w+3,yt);c.lineTo(g.plot.x+g.plot.w+3,yb2);c.lineTo(g.plot.x+g.plot.w-5,yb2);c.stroke();c.fillStyle=col;c.font='700 12px system-ui';c.fillText(pct(n,N),g.plot.x+g.plot.w-44,(yt+yb2)/2+4)}}
function timeHist(g,ctx,q,data,col){const N=state.fam.n||1,bins=new Map();data.forEach(d=>{const k=Math.floor((d.t-ctx.s.formed)/15)*15+ctx.s.formed;bins.set(k,(bins.get(k)||0)+1)});const y0=g.plot.y+g.plot.h+25,h=Math.max(20,g.bottom-32),max=Math.max(1,...bins.values());for(const[t,n]of bins){const x0=q.X(t),x1=q.X(t+15),bh=h*n/max;c.fillStyle=col;c.globalAlpha=.28;c.fillRect(x0,y0+h-bh,Math.max(2,x1-x0-1),bh);c.globalAlpha=1;if(x1-x0>28&&n){c.fillStyle=colors.muted;c.font='10px system-ui';c.fillText(pct(n,N),x0+2,y0+h-bh+10)}state.hit.push({k:'tbin',x:x0,y:y0,w:x1-x0,yh:h,t,n,N})}}
function pathMap(g,ctx,q){const f=state.fam,N=f.n||1,grid=f.path_grid||[];grid.forEach((T,j)=>{const counts=new Map();f.members.forEach(m=>{const u=m.path_cl?.[j];if(u==null)return;const k=Math.floor((u+1e-10)*10)/10;counts.set(k,(counts.get(k)||0)+1)});for(const[k,n]of counts){const x0=q.X(T),x1=q.X(T+5),y0=Math.min(q.Y(projected(k)),q.Y(projected(k+.1))),y1=Math.max(q.Y(projected(k)),q.Y(projected(k+.1))),a=Math.min(.78,.08+.7*n/N);c.fillStyle='rgba(119,169,255,'+a+')';c.fillRect(x0,y0,Math.max(1,x1-x0),Math.max(2,y1-y0));state.hit.push({k:'cell',x:x0,y:y0,w:Math.max(2,x1-x0),yh:Math.max(3,y1-y0),T,bin:k,n,N})}})}
function empty(g,f){c.fillStyle=colors.muted;c.font='14px system-ui';c.fillText(f?.status==='waiting'?'Подтверждения ещё нет — исходный слепок семьи не определён.':'Нет доступного слепка для выбранного состояния.',80,80)}
function move(e){const r=cv.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let best=null,bd=1e9;for(const h of state.hit){if(h.k==='event'){const d=(x-h.x)**2+(y-h.y)**2;if(d<bd&&d<80){best=h;bd=d}}else if(x>=h.x&&x<=h.x+(h.w||0)&&y>=h.y&&y<=h.y+(h.yh||0)){best=h;break}}state.hover=best;if(!best){tip.hidden=true;return}tip.hidden=false;tip.style.left=Math.min(r.width-250,x+12)+'px';tip.style.top=Math.max(4,y-10)+'px';tip.innerHTML=hoverHtml(best)}
function hoverHtml(h){if(h.k==='event'){const name=state.mode==='R'?'Максимальный откат':'Максимальное расширение';return'<b>'+name+'</b><br>'+h.d.u.toFixed(2)+' SD · '+clk(h.d.t)+'<br><span style="color:#8d98a8">одно событие одной исторической сессии</span>'}if(h.k==='pbin')return'<b>'+pct(h.n,h.N)+'</b> семьи<br>'+h.bin.toFixed(1)+'…'+(h.bin+.1).toFixed(1)+' SD<br><span style="color:#8d98a8">событие '+state.mode+' в ценовой полосе</span>';if(h.k==='tbin')return'<b>'+pct(h.n,h.N)+'</b> семьи<br>'+clk(h.t)+'–'+clk(h.t+15)+'<br><span style="color:#8d98a8">время события '+state.mode+'</span>';if(h.k==='cell')return'<b>'+pct(h.n,h.N)+'</b> семьи<br>'+clk(h.T)+' · '+h.bin.toFixed(1)+'…'+(h.bin+.1).toFixed(1)+' SD<br><span style="color:#8d98a8">закрытие на этой M5</span>';return''}
function click(){const h=state.hover;if(h?.k==='pbin'&&state.mode!=='PATH'){state.selected={type:'price',bin:h.bin};draw()}}
function renderPanel(){const f=state.fam;if(!f||f.status!=='ok'){panel.innerHTML='<h3>SEM-1.0</h3><div class="note">'+esc(f?.status||'Нет данных')+'</div>';return}const mode=state.mode,brk=f.mode==='brk';let html='<h3>'+esc(f.cond)+'</h3><div class="kv"><span>Семья</span><b>'+f.n+' сессий</b></div><div class="kv"><span>Срез</span><b>'+clk(f.obs)+'</b></div><div class="note">Исходный слепок фиксирован. Смена M5 не пересчитывает R/X.</div>';if(!brk&&f.outcome){const o=f.outcome;html+='<h4>Исход DR</h4><div class="outcome"><div class="card"><b>'+pct(o.held,f.n)+'</b><span>удержал</span></div><div class="card"><b>'+pct(o.broken,f.n)+'</b><span>сломался</span></div><div class="card"><b>'+pct(o.unknown+o.no_period,f.n)+'</b><span>неизвестно</span></div></div>'}if(mode==='PATH'){html+='<h4>Путь семьи</h4><div class="note">Каждая колонка M5 — положение закрытий той же семьи по общим часам. Это не карта экстремумов и не прогноз из текущей цены.</div>'}else{const label=mode==='R'?(brk?'Против слома · граница':'Максимальный откат R'):(brk?'По слому · граница':'Максимальное расширение X'),known=eventData().length,unk=f.n-known;html+='<h4>'+label+'</h4><div class="kv"><span>Известные события</span><b>'+known+' / '+f.n+'</b></div><div class="kv"><span>Неизвестно</span><b>'+pct(unk,f.n)+'</b></div><div class="note">'+(mode==='R'?'Самая глубокая направленная точка после собственного старта исторической сессии до конца блока.':'Самая дальняя направленная точка после собственного старта исторической сессии до конца блока.')+'</div>';if(state.selected?.type==='price'){const n=eventData().filter(x=>x.u>=state.selected.bin&&x.u<state.selected.bin+.1).length;html+='<h4>Выбранная ценовая зона</h4><div class="sel"><b>'+pct(n,f.n)+'</b> всей семьи<br>'+state.selected.bin.toFixed(1)+'…'+(state.selected.bin+.1).toFixed(1)+' SD<div class="note">Доля события в полосе, не «сила уровня» и не подтверждённый кластер.</div></div>'}else html+='<h4>Область</h4><div class="note">Нажмите на столбик возле цены, чтобы выбрать ценовую полосу. Автоматического «главного кластера» в прототипе нет.</div>'}html+='<h4>Статус</h4><div class="note">DR-LAB-SEM-1.0 · отдельный образец. First-touch/KDE из №22 не используются как главный объект.</div>';panel.innerHTML=html}
init()})();